apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  index.html: |
    <html>
    <head>
      <title>Welcome to my website</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
    </body>
    </html>